# Generated by Django 3.1.2 on 2020-12-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0002_questionanswer_surveyanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='the_survey',
            new_name='survey',
        ),
    ]
